FROM python:3.9-slim

WORKDIR /app

RUN python -m venv /app/venv

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app requirements.txt ./models ./run.py ./

ENV VIRTUAL_ENV=/app/venv
ENV PATH="/app/venv/bin:$PATH"

EXPOSE 8000

CMD ["python", "run.py"]
