FROM python:3.12-slim

WORKDIR /app

# RUN python -m venv venv

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY ./src ./

ENV VIRTUAL_ENV=/app/venv
ENV PATH="/app/venv/bin:$PATH"

EXPOSE 8000

CMD ["python", "run.py"]
