server:
  addr: :8080
  mode: development
  read_timeout: 5
  write_timeout: 5
  ctx_timeout: 10
  debug: false

logger:
  mode: development
  disable_caller: false
  disable_stacktrace: false
  encoding: console
  level: info

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: gopix_dev
  ssl: false
  driver: pgx
