server:
  addr: :8080
  mode: development
  read_timeout: 5
  write_timeout: 5
  ctx_timeout: 10
  debug: false
  cookie:
    name: token
    expire: 86400
    secure: false
    http_only: true
  session:
    expire: 86400
    secret: secret

logger:
  mode: development
  disable_caller: false
  disable_stacktrace: false
  encoding: console
  level: info

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: gopix_dev
  ssl: false
  driver: pgx

redis:
  redis_addr: redis:6379
  redis_pass: ""
  redis_db: 0
  redis_default_db: 0
  min_idle_conns: 10
  pool_size: 100
  pool_timeout: 240

s3:
  endpoint: https://<account_id>.r2.cloudflarestorage.com/gopix # cloudflare r2
  bucket: gopix
  region: auto
  access_key: access_key
  secret_access_key: secret_access_key
  force_path_style: true